<section class="geolocdestok">
  <span class="glyphicon glyphicon-map-marker"></span>
  <span>Maracaibo, Venezuela</span>
</section>
<section class="lineatopfooter"></section>
<footer class="container">
  <section class="row">
    <section class="col-md-4">
       <img class="logofooter"src="img/logo8.png">
    </section>
    <section class="col-md-2">
      <ul>
        <li class="espaciadofotinfo">ACERCA DE</li>
        <li><a href="">Sobre Nosotros</a></li>
        <li><a href="">Horarios</a></li>
        <li><a href="">Términos de servicio</a></li>
        <li><a href="">Política de privacidad</a></li>
      </ul>
    </section>
    <section class="col-md-2">
       <ul>
        <li class="espaciadofotinfo">SOPORTE</li>
        <li><a href="">Contactar a nuestro soporte</a></li>
        <li><a href="">Preguntas más frecuentes</a></li>
        <li><a href="">Guías</a></li>
        <li><a href="">He olvidado la contraseña</a></li>
      </ul>
    </section>
    <section class="col-md-2">
       <ul>
        <li class="espaciadofotinfo">SERVICIOS</li>
        <li><a href=""><span class="iconovenezuela"><img src="img/ven.png"></span>Venezuela</a></li>
        <li><a href="">Afiliados</a></li>
        <li><a href="">Blog</a></li>
      </ul>
    </section>
    <section class="col-md-2">
       <ul>
        <li class="espaciadofotinfo">SIGANOS</li>
        <li><a href=""><span class="icofacebook"><img src="icon/icons8-facebook-f.svg"></span>Facebook</a></li>
        <li><a href=""><span class="icoinstagram"><img src="icon/icons8-instagram-old.svg"></span>Instagram</a></li>
      </ul>
    </section>
  </section>
</footer>
<a href="https://youtu.be/m1IU7zjl1k4" id="youtube"><i class="fa fa-youtube-play"></i></a>
  <script src="js/ie-emulation-modes-warning.js"></script>
  <script src="js/jquery.min.js"></script>
  <script src="js/ie10-viewport-bug-workaround.js"></script>
  <script src="js/bootstrap.min.js"></script>
  <script  src="js/indexmodtransf.js"></script>
  <script src="js/modernizr.min.js" type="text/javascript"></script>
</body>
</html>