<!DOCTYPE html>
<html>
<head>
	<link rel="stylesheet" href="css/stylespassword.css">
	<link href="css/bootstrap.min.css" rel="stylesheet"> 
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title></title>
</head>
<body>
	<section class="bajapasvalidador">
	<h1>Introducir contraseña</h1>
	<form action="#">
    	<span class="glyphicon glyphicon-lock"></span>
    	<input type="password" placeholder="Contraseña" required="required"/>
   		<section class="btnbutton">
    		<button class="btn btn-success">Aceptar</button>
    	</section>
    </form>
    <p>* Por motivos de seguiradad debe introducir su contraseña para validad la operación</p>
</section>
</body>
</html>
