<!DOCTYPE html>
<html>
<head>
	<link rel="stylesheet" href="css/stylespassword.css">
	<link href="css/bootstrap.min.css" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1"> 
	<title></title>
</head>
<body>
	<section class="bajapasvalidadorpin">
    <section class="generadorcodigo">
    <section class="labeles">
        <label data-toggle="tooltip" data-placement="bottom" title="Coordenadas">3A</label>
        <span>+</span>
        <label data-toggle="tooltip" data-placement="bottom" title="Codigo PIN de la cartera">PIN</label>
    </section>
    </section>
	<h1>Introducir combinación</h1>
	<form action="#">
    	<span class="glyphicon glyphicon-lock"></span>
    	<input type="password" placeholder="Código + PIN" required="required" maxlength="4" />
   		<section class="btnbutton">
    		<button class="btn btn-success">Aceptar</button>
    	</section>
    </form>
    <p>* Por motivos de seguiradad debe introducir su contraseña para validad la operación</p>
</section>
<script src="js/jquery.min.js"></script>
<script src="js/pin.js"></script>
<script src="js/bootstrap.min.js"></script>
</body>
</html>
